services:
  redisdb:
    image: redis
    ports:
      - '6379:6379'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_USER: aditya
      POSTGRES_DB: ridiet
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: ridiet_server
    depends_on:
      - db
      - redisdb
    ports:
      - '4002:4001'
